name: build and deploy mkdocs to github pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.4.0 mkdocs-material==8.5.6
      - run: echo "training.arcadiascience.com" > CNAME
      - run: mkdocs gh-deploy --force
